### ISSUE TITLE
external url 

### ISSUE THREAD

**Issue by PanelTrader** [q-m/cordova-web-wrap#3]
Hi ... I need help for back to app from external url with querystring. Please help. Thnks

**Comment by wvengen** [comment]
It looks like you mean that you want to navigate away from your Cordova app, and then click a link (or do some other action) in the other app that opens the Cordova app, right?

That would need some functionality like universal links or a custom URL scheme.
[Launch callback data](https://github.com/nchutchind/cordova-plugin-app-launcher#launcherlaunch-success-callback-data) can also be an solution in some cases.
