### ISSUE TITLE
** BUILD FAILED **

### ISSUE THREAD

**Issue by jet10000** [q-m/cordova-web-wrap#4]
** BUILD FAILED **

The following build commands failed:
	CompileAssetCatalog /Users/jet/Desktop/cordova-web-wrap/platforms/ios/build/emulator/Example.app /Users/jet/Desktop/cordova-web-wrap/platforms/ios/Example/Images.xcassets
(1 failure)
xcodebuild: Command failed with exit code 65

**Comment by timsayshey** [comment]
You need to regenerate the icons in the correct sizes.
